// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPaths(arg1:Array<string>):Promise<Array<main.VideoItem>>;

export function AppVersion():Promise<string>;

export function CancelFile(arg1:string):Promise<void>;

export function CancelProcessing():Promise<void>;

export function CheckFFmpeg():Promise<main.FFmpegStatus>;

export function CheckUpdates():Promise<main.UpdateStatus>;

export function ClearFiles():Promise<void>;

export function DefaultSettings():Promise<main.Settings>;

export function ExportPresets(arg1:string):Promise<string>;

export function GetUpdateStatus():Promise<main.UpdateStatus>;

export function ImportPresets():Promise<string>;

export function InstallFFmpeg():Promise<void>;

export function ListFiles():Promise<Array<main.VideoItem>>;

export function PickFFmpeg():Promise<main.FFmpegStatus>;

export function RemoveFile(arg1:string):Promise<void>;

export function StartFile(arg1:string,arg2:main.Settings):Promise<void>;

export function StartProcessing(arg1:main.Settings):Promise<void>;
