// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function CPUCount() {
  return window['go']['main']['App']['CPUCount']();
}

export function CancelFile(arg1) {
  return window['go']['main']['App']['CancelFile'](arg1);
}

export function CancelProcessing() {
  return window['go']['main']['App']['CancelProcessing']();
}

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function CheckUpdates() {
  return window['go']['main']['App']['CheckUpdates']();
}

export function ClearFiles() {
  return window['go']['main']['App']['ClearFiles']();
}

export function DefaultSettings() {
  return window['go']['main']['App']['DefaultSettings']();
}

export function ExportPresets(arg1) {
  return window['go']['main']['App']['ExportPresets'](arg1);
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function HasPreviewProxy(arg1) {
  return window['go']['main']['App']['HasPreviewProxy'](arg1);
}

export function ImportPresets() {
  return window['go']['main']['App']['ImportPresets']();
}

export function InstallFFmpeg() {
  return window['go']['main']['App']['InstallFFmpeg']();
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function MakePreviewProxy(arg1) {
  return window['go']['main']['App']['MakePreviewProxy'](arg1);
}

export function PickFFmpeg() {
  return window['go']['main']['App']['PickFFmpeg']();
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function StartFile(arg1, arg2) {
  return window['go']['main']['App']['StartFile'](arg1, arg2);
}

export function StartProcessing(arg1) {
  return window['go']['main']['App']['StartProcessing'](arg1);
}
